services:
  takimbox:
    image: alexdevuwu/takimbox
    container_name: takimbox
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3006:3000"
    volumes:
      - type: bind
        source: ./takimbox.db
        target: /app/takimbox.db
      - ./.env:/app/.env
