services:
  takimbox:
    image: alexdevuwu/takimbox
    container_name: takimbox
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3006:3000"
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env:ro
    restart: unless-stopped

volumes:
  sqlite_data: