version: "3.8"

services:
  takimbox:
    image: alexdevuwu/takimbox
    container_name: takimbox
    ports:
      - "3006:3000"
    volumes:
      - ./takimbox.db:/app/takimbox.db
      - ./.env:/app/.env
