services:
  takimbox:
    image: alexdevuwu/takimbox
    container_name: takimbox
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3006:3000"
    volumes:
      - ./takimbox.db:/app/takimbox.db
      - ./.env:/app/.env
